# Generated by Django 6.0.8 on 2026-09-05 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('device_uid', models.CharField(max_length=128, unique=True)),
                ('device_type', models.CharField(choices=[('SHELLY', 'Shelly'), ('ESP32', 'ESP32'), ('LILYGO', 'LILYGO'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('api_key', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_uid', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('sensor_type', models.CharField(choices=[('TEMPERATURE', 'Temperature'), ('HUMIDITY', 'Humidity'), ('DOOR', 'Door'), ('LEAK', 'Leak'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='devices.device')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('device', 'sensor_uid'), name='uniq_device_sensor_uid')],
            },
        ),
    ]
