# Generated by Django 6.0.8 on 2026-09-05 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_uid', models.CharField(max_length=128)),
                ('reading_type', models.CharField(max_length=64)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('text_value', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('measured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='devices.sensor')),
            ],
            options={
                'ordering': ['-measured_at', '-id'],
                'indexes': [models.Index(fields=['device', 'measured_at'], name='tel_device_measured_idx'), models.Index(fields=['sensor', 'measured_at'], name='tel_sensor_measured_idx'), models.Index(fields=['received_at'], name='tel_received_at_idx')],
            },
        ),
    ]
