# Generated by Django 6.0.8 on 2026-09-05 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryreading',
            name='reading_uid',
            field=models.CharField(blank=True, help_text='Device-generated id used for idempotent retries after offline flush.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='telemetryreading',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='telemetryreading',
            constraint=models.UniqueConstraint(condition=models.Q(('reading_uid__isnull', False)), fields=('device', 'reading_uid'), name='uniq_device_reading_uid'),
        ),
    ]
